# Generated by Django 4.0.3 on 2022-04-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_before_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/productsImages/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageproduct', to='products.product')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
