# Generated by Django 4.0.3 on 2022-05-14 23:50

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=products.models.generate_id_length, editable=False, max_length=7),
        ),
    ]
